//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.massiveprocess.massiveprocessws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OLifEExtensionResponse_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OLifEExtensionResponse_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TxnId" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TxnId_Type"/>
 *         &lt;element name="SrceCountry" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}SrceCountry_Type"/>
 *         &lt;element name="SrceCompany" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}SrceCompany_Type"/>
 *         &lt;element name="SrceSystem" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}SrceSystem_Type"/>
 *         &lt;element name="ResultInfoErrorType" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}ResultInfoErrorType_Type" minOccurs="0"/>
 *         &lt;element name="TransElapsedExeTime" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TransElapsedExeTime_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OLifEExtensionResponse_Type", propOrder = {
    "txnId",
    "srceCountry",
    "srceCompany",
    "srceSystem",
    "resultInfoErrorType",
    "transElapsedExeTime"
})
public class OLifEExtensionResponseType {

    @XmlElement(name = "TxnId")
    protected long txnId;
    @XmlElement(name = "SrceCountry", required = true)
    protected String srceCountry;
    @XmlElement(name = "SrceCompany", required = true)
    protected String srceCompany;
    @XmlElement(name = "SrceSystem", required = true)
    protected String srceSystem;
    @XmlElement(name = "ResultInfoErrorType")
    protected String resultInfoErrorType;
    @XmlElement(name = "TransElapsedExeTime", required = true)
    protected String transElapsedExeTime;

    /**
     * Gets the value of the txnId property.
     * 
     */
    public long getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     */
    public void setTxnId(long value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the srceCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceCountry() {
        return srceCountry;
    }

    /**
     * Sets the value of the srceCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceCountry(String value) {
        this.srceCountry = value;
    }

    /**
     * Gets the value of the srceCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceCompany() {
        return srceCompany;
    }

    /**
     * Sets the value of the srceCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceCompany(String value) {
        this.srceCompany = value;
    }

    /**
     * Gets the value of the srceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceSystem() {
        return srceSystem;
    }

    /**
     * Sets the value of the srceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceSystem(String value) {
        this.srceSystem = value;
    }

    /**
     * Gets the value of the resultInfoErrorType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultInfoErrorType() {
        return resultInfoErrorType;
    }

    /**
     * Sets the value of the resultInfoErrorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultInfoErrorType(String value) {
        this.resultInfoErrorType = value;
    }

    /**
     * Gets the value of the transElapsedExeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransElapsedExeTime() {
        return transElapsedExeTime;
    }

    /**
     * Sets the value of the transElapsedExeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransElapsedExeTime(String value) {
        this.transElapsedExeTime = value;
    }

}
