//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.massiveprocess.massiveprocessws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OLifE_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OLifE_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BaseFile" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}BaseFile_Type"/>
 *         &lt;element name="FileName" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}FileName_Type"/>
 *         &lt;element name="FileExtension" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}FileExtension_Type"/>
 *         &lt;element name="FileSize" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}FileSize_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OLifE_Type", propOrder = {
    "baseFile",
    "fileName",
    "fileExtension",
    "fileSize"
})
public class OLifEType {

    @XmlElement(name = "BaseFile", required = true)
    protected byte[] baseFile;
    @XmlElement(name = "FileName", required = true)
    protected String fileName;
    @XmlElement(name = "FileExtension", required = true)
    protected String fileExtension;
    @XmlElement(name = "FileSize", required = true)
    protected String fileSize;

    /**
     * Gets the value of the baseFile property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBaseFile() {
        return baseFile;
    }

    /**
     * Sets the value of the baseFile property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBaseFile(byte[] value) {
        this.baseFile = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileExtension() {
        return fileExtension;
    }

    /**
     * Sets the value of the fileExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileExtension(String value) {
        this.fileExtension = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSize(String value) {
        this.fileSize = value;
    }

}
