//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.massiveprocess.massiveprocessws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResultInfo_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultInfo_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResultInfoCode" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}ResultInfoCode_Type" minOccurs="0"/>
 *         &lt;element name="ResultInfoDesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResultInfoSysMessageCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ResultInfoSeverity" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}ResultInfoSeverity_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultInfo_Type", propOrder = {
    "resultInfoCode",
    "resultInfoDesc",
    "resultInfoSysMessageCode",
    "resultInfoSeverity"
})
public class ResultInfoType {

    @XmlElement(name = "ResultInfoCode")
    protected String resultInfoCode;
    @XmlElement(name = "ResultInfoDesc", required = true)
    protected String resultInfoDesc;
    @XmlElement(name = "ResultInfoSysMessageCode", required = true)
    protected String resultInfoSysMessageCode;
    @XmlElement(name = "ResultInfoSeverity", required = true)
    protected String resultInfoSeverity;

    /**
     * Gets the value of the resultInfoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultInfoCode() {
        return resultInfoCode;
    }

    /**
     * Sets the value of the resultInfoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultInfoCode(String value) {
        this.resultInfoCode = value;
    }

    /**
     * Gets the value of the resultInfoDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultInfoDesc() {
        return resultInfoDesc;
    }

    /**
     * Sets the value of the resultInfoDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultInfoDesc(String value) {
        this.resultInfoDesc = value;
    }

    /**
     * Gets the value of the resultInfoSysMessageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultInfoSysMessageCode() {
        return resultInfoSysMessageCode;
    }

    /**
     * Sets the value of the resultInfoSysMessageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultInfoSysMessageCode(String value) {
        this.resultInfoSysMessageCode = value;
    }

    /**
     * Gets the value of the resultInfoSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultInfoSeverity() {
        return resultInfoSeverity;
    }

    /**
     * Sets the value of the resultInfoSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultInfoSeverity(String value) {
        this.resultInfoSeverity = value;
    }

}
