//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.massiveprocess.massiveprocessws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TXLifeRequest_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TXLifeRequest_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransRefGUID" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TransRefGUID_Type"/>
 *         &lt;element name="TransType" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TransType_Type"/>
 *         &lt;element name="TransExeDate" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TransExeDate_Type"/>
 *         &lt;element name="TransExeTime" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TransExeTime_Type"/>
 *         &lt;element name="TestIndicator" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}TestIndicator_Type" minOccurs="0"/>
 *         &lt;element name="OLifE" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}OLifE_Type"/>
 *         &lt;element name="OLifEExtension" type="{http://www.metlife.com.mx/schema/MassiveProcess/MassiveProcessWS}OLifEExtension_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TXLifeRequest_Type", propOrder = {
    "transRefGUID",
    "transType",
    "transExeDate",
    "transExeTime",
    "testIndicator",
    "oLifE",
    "oLifEExtension"
})
public class TXLifeRequestType {

    @XmlElement(name = "TransRefGUID", required = true)
    protected String transRefGUID;
    @XmlElement(name = "TransType", required = true)
    protected TransTypeType transType;
    @XmlElement(name = "TransExeDate", required = true)
    protected String transExeDate;
    @XmlElement(name = "TransExeTime", required = true)
    protected String transExeTime;
    @XmlElement(name = "TestIndicator")
    protected TestIndicatorType testIndicator;
    @XmlElement(name = "OLifE", required = true)
    protected OLifEType oLifE;
    @XmlElement(name = "OLifEExtension", required = true)
    protected OLifEExtensionType oLifEExtension;

    /**
     * Gets the value of the transRefGUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransRefGUID() {
        return transRefGUID;
    }

    /**
     * Sets the value of the transRefGUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransRefGUID(String value) {
        this.transRefGUID = value;
    }

    /**
     * Gets the value of the transType property.
     * 
     * @return
     *     possible object is
     *     {@link TransTypeType }
     *     
     */
    public TransTypeType getTransType() {
        return transType;
    }

    /**
     * Sets the value of the transType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransTypeType }
     *     
     */
    public void setTransType(TransTypeType value) {
        this.transType = value;
    }

    /**
     * Gets the value of the transExeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransExeDate() {
        return transExeDate;
    }

    /**
     * Sets the value of the transExeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransExeDate(String value) {
        this.transExeDate = value;
    }

    /**
     * Gets the value of the transExeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransExeTime() {
        return transExeTime;
    }

    /**
     * Sets the value of the transExeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransExeTime(String value) {
        this.transExeTime = value;
    }

    /**
     * Gets the value of the testIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link TestIndicatorType }
     *     
     */
    public TestIndicatorType getTestIndicator() {
        return testIndicator;
    }

    /**
     * Sets the value of the testIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestIndicatorType }
     *     
     */
    public void setTestIndicator(TestIndicatorType value) {
        this.testIndicator = value;
    }

    /**
     * Gets the value of the oLifE property.
     * 
     * @return
     *     possible object is
     *     {@link OLifEType }
     *     
     */
    public OLifEType getOLifE() {
        return oLifE;
    }

    /**
     * Sets the value of the oLifE property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLifEType }
     *     
     */
    public void setOLifE(OLifEType value) {
        this.oLifE = value;
    }

    /**
     * Gets the value of the oLifEExtension property.
     * 
     * @return
     *     possible object is
     *     {@link OLifEExtensionType }
     *     
     */
    public OLifEExtensionType getOLifEExtension() {
        return oLifEExtension;
    }

    /**
     * Sets the value of the oLifEExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link OLifEExtensionType }
     *     
     */
    public void setOLifEExtension(OLifEExtensionType value) {
        this.oLifEExtension = value;
    }

}
