//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.sendmail.sendmailws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldKeys_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FieldKeys_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FieldKeyVal" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}FieldKeyVal_Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FieldKeys_Type", propOrder = {
    "fieldKeyVal"
})
public class FieldKeysType {

    @XmlElement(name = "FieldKeyVal", required = true)
    protected List<FieldKeyValType> fieldKeyVal;

    /**
     * Gets the value of the fieldKeyVal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldKeyVal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldKeyVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldKeyValType }
     * 
     * 
     */
    public List<FieldKeyValType> getFieldKeyVal() {
        if (fieldKeyVal == null) {
            fieldKeyVal = new ArrayList<FieldKeyValType>();
        }
        return this.fieldKeyVal;
    }

}
