//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.sendmail.sendmailws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageKeys_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageKeys_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ImageKeyVal" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}ImageKeyVal_Type" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageKeys_Type", propOrder = {
    "imageKeyVal"
})
public class ImageKeysType {

    @XmlElement(name = "ImageKeyVal", required = true)
    protected List<ImageKeyValType> imageKeyVal;

    /**
     * Gets the value of the imageKeyVal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageKeyVal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageKeyVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageKeyValType }
     * 
     * 
     */
    public List<ImageKeyValType> getImageKeyVal() {
        if (imageKeyVal == null) {
            imageKeyVal = new ArrayList<ImageKeyValType>();
        }
        return this.imageKeyVal;
    }

}
