//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.sendmail.sendmailws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OLifE_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OLifE_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MailData" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}MailData_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OLifE_Type", propOrder = {
    "mailData"
})
public class OLifEType {

    @XmlElement(name = "MailData", required = true)
    protected MailDataType mailData;

    /**
     * Gets the value of the mailData property.
     * 
     * @return
     *     possible object is
     *     {@link MailDataType }
     *     
     */
    public MailDataType getMailData() {
        return mailData;
    }

    /**
     * Sets the value of the mailData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailDataType }
     *     
     */
    public void setMailData(MailDataType value) {
        this.mailData = value;
    }

}
