//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.sendmail.sendmailws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OLifEExtension_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OLifEExtension_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SrceCountry" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}SrceCountry_Type"/>
 *         &lt;element name="SrceCompany" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}SrceCompany_Type"/>
 *         &lt;element name="SrceSystem" type="{http://www.metlife.com.mx/schema/SendMail/SendMailWS}SrceSystem_Type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OLifEExtension_Type", propOrder = {
    "srceCountry",
    "srceCompany",
    "srceSystem"
})
public class OLifEExtensionType {

    @XmlElement(name = "SrceCountry", required = true)
    protected String srceCountry;
    @XmlElement(name = "SrceCompany", required = true)
    protected String srceCompany;
    @XmlElement(name = "SrceSystem", required = true)
    protected String srceSystem;

    /**
     * Gets the value of the srceCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceCountry() {
        return srceCountry;
    }

    /**
     * Sets the value of the srceCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceCountry(String value) {
        this.srceCountry = value;
    }

    /**
     * Gets the value of the srceCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceCompany() {
        return srceCompany;
    }

    /**
     * Sets the value of the srceCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceCompany(String value) {
        this.srceCompany = value;
    }

    /**
     * Gets the value of the srceSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrceSystem() {
        return srceSystem;
    }

    /**
     * Sets the value of the srceSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrceSystem(String value) {
        this.srceSystem = value;
    }

}
