//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.metlife.com.mx/schema/SendMail/SendMailWS")
package mx.com.metlife.schema.sendmail.sendmailws;
