//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.ws.hubcomunicaciones;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;



@WebServiceClient(name = "MxHUBCOM.WSD.wsdHubComunicacionesSF", targetNamespace = "http://www.metlife.com.mx/ws/HubComunicaciones", wsdlLocation = "file:wsdl/wsdHubComunicacionesSF.wsdl")
public class MxHUBCOMWSDWsdHubComunicacionesSF extends Service {

    private final static URL MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_WSDL_LOCATION;
    private final static WebServiceException MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_EXCEPTION;
    private final static QName MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_QNAME = new QName("http://www.metlife.com.mx/ws/HubComunicaciones", "MxHUBCOM.WSD.wsdHubComunicacionesSF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	
        	URL baseUrl = MxHUBCOMWSDWsdHubComunicacionesSF.class.getResource("/mx/com/metlife/ws/client/util/wsdl");
            url = new URL(baseUrl, "wsdHubComunicacionesSF.wsdl");
            //url = new URL("file:wsdl/wsdHubComunicacionesSF.wsdl");
        	//url = new URL("file:/Users/Apple/Desktop/AgentesSSA/Notificaciones_MXGES/src/main/webapp/wsdl/wsdHubComunicacionesSF.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_WSDL_LOCATION = url;
        MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_EXCEPTION = e;
    }
    
    public WsdHubComunicacionesSFPortType getPortType(String endpoint){
    	WsdHubComunicacionesSFPortType port= getMxHUBCOMWSDWsdHubComunicacionesSFPort();
    	BindingProvider bp= (BindingProvider) port;
    	Map<String, Object> context= bp.getRequestContext();
    	context.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpoint);

    	return port;
    	
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF() {
        super(__getWsdlLocation(), MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_QNAME);
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF(WebServiceFeature... features) {
        super(__getWsdlLocation(), MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_QNAME);
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF(URL wsdlLocation) {
        super(wsdlLocation, MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_QNAME);
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_QNAME);
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MxHUBCOMWSDWsdHubComunicacionesSF(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WsdHubComunicacionesSFPortType
     */
    @WebEndpoint(name = "MxHUBCOM_WSD_wsdHubComunicacionesSF_Port")
    public WsdHubComunicacionesSFPortType getMxHUBCOMWSDWsdHubComunicacionesSFPort() {
        return super.getPort(new QName("http://www.metlife.com.mx/ws/HubComunicaciones", "MxHUBCOM_WSD_wsdHubComunicacionesSF_Port"), WsdHubComunicacionesSFPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsdHubComunicacionesSFPortType
     */
    @WebEndpoint(name = "MxHUBCOM_WSD_wsdHubComunicacionesSF_Port")
    public WsdHubComunicacionesSFPortType getMxHUBCOMWSDWsdHubComunicacionesSFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.metlife.com.mx/ws/HubComunicaciones", "MxHUBCOM_WSD_wsdHubComunicacionesSF_Port"), WsdHubComunicacionesSFPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_EXCEPTION!= null) {
            throw MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_EXCEPTION;
        }
        return MXHUBCOMWSDWSDHUBCOMUNICACIONESSF_WSDL_LOCATION;
    }

}
