//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.ws.hubcomunicaciones;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mx.com.metlife.schema.select.selectws.TXLifeRequestType;


/**
 * <p>Java class for selectRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.metlife.com.mx/schema/Select/SelectWS}TXLifeRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectRequest", propOrder = {
    "txLifeRequest"
})
public class SelectRequest {

    @XmlElement(name = "TXLifeRequest", namespace = "http://www.metlife.com.mx/schema/Select/SelectWS", required = true)
    protected TXLifeRequestType txLifeRequest;

    /**
     * Gets the value of the txLifeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TXLifeRequestType }
     *     
     */
    public TXLifeRequestType getTXLifeRequest() {
        return txLifeRequest;
    }

    /**
     * Sets the value of the txLifeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TXLifeRequestType }
     *     
     */
    public void setTXLifeRequest(TXLifeRequestType value) {
        this.txLifeRequest = value;
    }

}
