//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.ws.hubcomunicaciones;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import mx.com.metlife.schema.select.selectws.TXLifeResponseType;


/**
 * <p>Java class for selectResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selectResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.metlife.com.mx/schema/Select/SelectWS}TXLifeResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selectResponse", propOrder = {
    "txLifeResponse"
})
public class SelectResponse {

    @XmlElement(name = "TXLifeResponse", namespace = "http://www.metlife.com.mx/schema/Select/SelectWS", required = true)
    protected TXLifeResponseType txLifeResponse;

    /**
     * Gets the value of the txLifeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link TXLifeResponseType }
     *     
     */
    public TXLifeResponseType getTXLifeResponse() {
        return txLifeResponse;
    }

    /**
     * Sets the value of the txLifeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link TXLifeResponseType }
     *     
     */
    public void setTXLifeResponse(TXLifeResponseType value) {
        this.txLifeResponse = value;
    }

}
