PROMPT *****  INICIO CARGA DE PROPIEDADES ******

INSERT INTO MXGES_CAT_METATABLAS ( CVE_TABLA, DES_TABLA, ESTATUS, NO_CLAVES, SW_PERMITE_CAMBIOS, NO_VALORES, CREADOPOR, FEC_CREACION) 
VALUES ('CAT_PROPERTIES', 'Catálogo de propiedades del sistema MXGES',  'A', 1, 'S', 1, 'MXGESAD', TRUNC(SYSDATE));           

INSERT INTO MXGES_CAT_VALORES (CLAVE_01, VALOR_01, VALOR_02, ESTATUS, CVE_TABLA) 
VALUES ('CONCURRENCE', 'Bandera para saber si se esta ejecutando un envío de notificaciones', 'N', 'A', 'CAT_PROPERTIES');

INSERT INTO MXGES_CAT_VALORES (CLAVE_01, VALOR_01, VALOR_02, ESTATUS, CVE_TABLA) 
VALUES ('REM_ACENTOS', 'Bandera que indica si a las notificaciones SMS se le quitaran los acentos', 'S', 'A', 'CAT_PROPERTIES');

PROMPT *****  INICIO CONFIGURACION PANTALLAS ******

INSERT INTO MXGES_SEG_PANTALLAS (ID_PANTALLA, DES_MENU, DES_PANTALLA, CREADO_POR, FEC_CREACION, OBSERVACIONES) 
VALUES (9, 'Configuración de SMS´s', 'Configuración de SMS´s',  'MXGESAD', TRUNC(SYSDATE), 'Pantalla para configurar las politicas de envío de SMS');

INSERT INTO MXGES_SEG_ROL_PANT ( SW_CONSULTA, ID_PANTALLA, CVE_ROL) 
VALUES ('1', 9,  'ADMINLOB');

COMMIT;

PROMPT *****  FINALIZO SCRIPT ******