//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.select.selectws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mx.com.metlife.schema.select.selectws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TXLifeResponse_QNAME = new QName("http://www.metlife.com.mx/schema/Select/SelectWS", "TXLifeResponse");
    private final static QName _TXLifeRequest_QNAME = new QName("http://www.metlife.com.mx/schema/Select/SelectWS", "TXLifeRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mx.com.metlife.schema.select.selectws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TXLifeRequestType }
     * 
     */
    public TXLifeRequestType createTXLifeRequestType() {
        return new TXLifeRequestType();
    }

    /**
     * Create an instance of {@link TXLifeResponseType }
     * 
     */
    public TXLifeResponseType createTXLifeResponseType() {
        return new TXLifeResponseType();
    }

    /**
     * Create an instance of {@link OLifEExtensionType }
     * 
     */
    public OLifEExtensionType createOLifEExtensionType() {
        return new OLifEExtensionType();
    }

    /**
     * Create an instance of {@link ResultInfoType }
     * 
     */
    public ResultInfoType createResultInfoType() {
        return new ResultInfoType();
    }

    /**
     * Create an instance of {@link OLifEExtensionResponseType }
     * 
     */
    public OLifEExtensionResponseType createOLifEExtensionResponseType() {
        return new OLifEExtensionResponseType();
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link ResultCodeType }
     * 
     */
    public ResultCodeType createResultCodeType() {
        return new ResultCodeType();
    }

    /**
     * Create an instance of {@link TestIndicatorType }
     * 
     */
    public TestIndicatorType createTestIndicatorType() {
        return new TestIndicatorType();
    }

    /**
     * Create an instance of {@link TransTypeType }
     * 
     */
    public TransTypeType createTransTypeType() {
        return new TransTypeType();
    }

    /**
     * Create an instance of {@link ResultInfoArrayType }
     * 
     */
    public ResultInfoArrayType createResultInfoArrayType() {
        return new ResultInfoArrayType();
    }

    /**
     * Create an instance of {@link TransResultType }
     * 
     */
    public TransResultType createTransResultType() {
        return new TransResultType();
    }

    /**
     * Create an instance of {@link OLifEType }
     * 
     */
    public OLifEType createOLifEType() {
        return new OLifEType();
    }

    /**
     * Create an instance of {@link OLifEResponseType }
     * 
     */
    public OLifEResponseType createOLifEResponseType() {
        return new OLifEResponseType();
    }

    /**
     * Create an instance of {@link ResultsType }
     * 
     */
    public ResultsType createResultsType() {
        return new ResultsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TXLifeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.metlife.com.mx/schema/Select/SelectWS", name = "TXLifeResponse")
    public JAXBElement<TXLifeResponseType> createTXLifeResponse(TXLifeResponseType value) {
        return new JAXBElement<TXLifeResponseType>(_TXLifeResponse_QNAME, TXLifeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TXLifeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.metlife.com.mx/schema/Select/SelectWS", name = "TXLifeRequest")
    public JAXBElement<TXLifeRequestType> createTXLifeRequest(TXLifeRequestType value) {
        return new JAXBElement<TXLifeRequestType>(_TXLifeRequest_QNAME, TXLifeRequestType.class, null, value);
    }

}
