//
// Generated By:JAX-WS RI 2.2.4-b01 (JAXB RI IBM 2.2.4-2)
//


package mx.com.metlife.schema.select.selectws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransResult_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransResult_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResultCode" type="{http://www.metlife.com.mx/schema/Select/SelectWS}ResultCode_Type"/>
 *         &lt;element name="RecordsFound" type="{http://www.metlife.com.mx/schema/Select/SelectWS}RecordsFound_Type" minOccurs="0"/>
 *         &lt;element name="ResultInfoArray" type="{http://www.metlife.com.mx/schema/Select/SelectWS}ResultInfoArray_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransResult_Type", propOrder = {
    "resultCode",
    "recordsFound",
    "resultInfoArray"
})
public class TransResultType {

    @XmlElement(name = "ResultCode", required = true)
    protected ResultCodeType resultCode;
    @XmlElement(name = "RecordsFound")
    protected String recordsFound;
    @XmlElement(name = "ResultInfoArray")
    protected ResultInfoArrayType resultInfoArray;

    /**
     * Gets the value of the resultCode property.
     * 
     * @return
     *     possible object is
     *     {@link ResultCodeType }
     *     
     */
    public ResultCodeType getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultCodeType }
     *     
     */
    public void setResultCode(ResultCodeType value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the recordsFound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordsFound() {
        return recordsFound;
    }

    /**
     * Sets the value of the recordsFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordsFound(String value) {
        this.recordsFound = value;
    }

    /**
     * Gets the value of the resultInfoArray property.
     * 
     * @return
     *     possible object is
     *     {@link ResultInfoArrayType }
     *     
     */
    public ResultInfoArrayType getResultInfoArray() {
        return resultInfoArray;
    }

    /**
     * Sets the value of the resultInfoArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultInfoArrayType }
     *     
     */
    public void setResultInfoArray(ResultInfoArrayType value) {
        this.resultInfoArray = value;
    }

}
